### ISSUE TITLE
Build a release for gdal 2.3+

### ISSUE THREAD

**Issue by yeesian** [JuliaGeo/GDALBuilder#3]
see https://github.com/yeesian/ArchGDAL.jl/pull/44#issuecomment-394742279

**Comment by visr** [comment]
On master it is already building gdal 2.3, but currently 4/8 builds fail, so I cannot tag a new release yet.

https://travis-ci.org/JuliaGeo/GDALBuilder/builds/401082301

The failing builds are
- `Linux(:i686, :glibc)`
- `Linux(:aarch64, :glibc)`
- `Linux(:armv7l, :glibc)`
- `Linux(:powerpc64le, :glibc)`

And all are failing because they cannot find both `libproj` and `libz`
```
/opt/arm-linux-gnueabihf/lib/gcc/arm-linux-gnueabihf/7.3.0/../../../../arm-linux-gnueabihf/bin/ld: warning: libproj.so.12, needed by /workspace/srcdir/gdal-2.3.1/.libs/libgdal.so, not found (try using -rpath or -rpath-link)
/opt/arm-linux-gnueabihf/lib/gcc/arm-linux-gnueabihf/7.3.0/../../../../arm-linux-gnueabihf/bin/ld: warning: libz.so.1, needed by /workspace/srcdir/gdal-2.3.1/.libs/libgdal.so, not found (try using -rpath or -rpath-link)
/workspace/srcdir/gdal-2.3.1/.libs/libgdal.so: undefined reference to `deflateInit_'
/workspace/srcdir/gdal-2.3.1/.libs/libgdal.so: undefined reference to `deflateInit2_'
/workspace/srcdir/gdal-2.3.1/.libs/libgdal.so: undefined reference to `pj_ctx_alloc'
/workspace/srcdir/gdal-2.3.1/.libs/libgdal.so: undefined reference to `pj_get_errno_ref'
```

Unless someone has any ideas, I'll just wait a bit and come back to it, and rerun Travis.

**Comment by visr** [comment]
Probably worth trying again after this is merged:
https://github.com/JuliaPackaging/BinaryBuilder.jl/tree/sf/bb8
