### ISSUE TITLE
Make OGR/GDAL command line utilities available

### ISSUE THREAD

**Issue by niclasmattsson** [JuliaGeo/GDALBuilder#6]
A number of useful utilities like `gdalinfo`, `ogrinfo` and `ogr2ogr` are installed by default to `packages\GDAL\vec6Y\deps\usr\bin`. These are great for diagnosing fields of your datasets and converting them between different formats. However, they won't run on my Windows system since two .DLL libraries are missing. But I managed to the utilities working after copying over `libstdc++-6.dll` and `libwinpthread-1.dll` from inside the GR and WinRPM packages. It would be nice if GDALbuilder provided these DLLs too.

**Comment by visr** [comment]
Ah but these two files are also in the julia bin dir (next to julia.exe). It is working for me since I have this folder in my path environment variable. Is it correct that you don't?

Not sure what we should do about this. I'm not sure copying in these if they already come distributed with julia is a great idea. Of course would be good to document this.

**Comment by niclasmattsson** [comment]
Wow. I do have the Julia bin folder on my PATH on my main computers at home and at work, but not on the laptop I was running all of the shapefile tests on. The utilities work after fixing the PATH. Close the issue if you like or leave it open as a reminder to add something to the docs, but I'm good now. Thanks!

**Comment by visr** [comment]
Ok glad that is working. See the linked PR where I tried adding a little bit of documentation on this.
